submit project
GDGM-Service/final-project pull request #17
Opened 2022-05-20 14:53 UTC by Cyjhud

2022-05-21 03:43 UTC, GDGM-Service approved these changes
不要删除别人的东西

2022-05-21 03:51 UTC, GDGM-Service requested changes
你只需要新建自己的文件夹就行，不需要删除别人的
如果不知道怎么恢复别人的文件可以先同步一下最新的仓库，然后强制覆盖

2022-05-22 05:57 UTC, Cyjhud commented
我的可以通过吗

2022-05-22 07:08 UTC, GDGM-Service reviewed
可以通过

2022-05-22 07:08 UTC, merged